services:
  - type: web
    name: yourmealbox
    runtime: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
