services:
  - type: web
    name: yourmealbox
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
